[general]
live_config_reload = true
import = [
    "~/.cache/alacritty/theme.toml"
]
ipc_socket = true

[window]
startup_mode = "SimpleFullscreen"
padding = { x = 5, y = 2 }

[font]
# Regular text looks bold, so use Light for regular and regular for bold:
normal = { family = "FiraCode Nerd Font", style = "Light" }
bold = { style = "Regular" }
size = 14
offset = { x = 1, y = 3 }

[keyboard]
bindings = [
  { key = "Enter", mods = "Command", action = "ToggleSimpleFullscreen" }
]

[mouse]
hide_when_typing = true

[[hints.enabled]]
command = "open"
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "O", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`\\\\]+|[a-zA-Z0-9_/.-]+\\.png"
